### ISSUE TITLE
Eddi only returns remaining boost time when its boosting

### ISSUE THREAD

**Issue by davidfhudson** [ashleypittman/mec#10]
zp.py line 220         self.remaining_boost_time = self._glimpse(data, 'rbt')

if Eddi isnt boosting I dont get a value in rbt and thus get : Exception has occurred: KeyError 'rbt'

{'r1a': 0, 'r2a': 0, 'rbc': 0, 'tp1': 127, 'tp2': 127} When not boosting
{'r1a': 0, 'r2a': 0, 'rbc': 0, 'rbt': 1186, 'tp1': 127, 'tp2': 127} When boosting

**Comment by ashleypittman** [comment]
Should be fixed in https://github.com/ashleypittman/mec/commit/0ef1cd0742df0d20fb6685a6d60b3dd026952926

I'm not sure why mine has it, perhaps it's because I experimented with a boost and cancelled it part way through.
