### ISSUE TITLE
Cannot use; get 401

### ISSUE THREAD

**Issue by kirillkovalenko** [ashleypittman/mec#20]
I tripple checked my `~/.zappirc`, but I still get `urllib.error.HTTPError: HTTP Error 401: digest auth failed`. Are there any known protocol changes that broke this project?

**Comment by ashleypittman** [comment]
I've checked today and the auto for me is still working correctly.

MyEnergi have changed the way they create credentials several times, it used to be serial number + password but now with the move to a common account you need to create a API key at `https://myaccount.myenergi.com/` and use that.  I migrated some time ago, it could perhaps be that you've been using the older style and they've finally switched it off?

**Comment by kirillkovalenko** [comment]
Thank you for the information. I'll continue my investigation and update this thread if I discover anything useful.

**Comment by kirillkovalenko** [comment]
It works with an API key. Thank you once again.
